### ISSUE TITLE
Question: is it possible to use a logger other than root?

### ISSUE THREAD

**Issue by schiric** [danielwegener/logback-kafka-appender#101]
Hi,
is it possible to use kafka-appender only with a specific logger specified in logback.xml file?
ES.

<appender name="KAFKA" class="com.github.danielwegener.logback.kafka.KafkaAppender">
      <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">-->
          <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
      </encoder>
      <topic>logback.test</topic>
      
      <keyingStrategy class="com.github.danielwegener.logback.kafka.keying.NoKeyKeyingStrategy" />
      
      <deliveryStrategy class="com.github.danielwegener.logback.kafka.delivery.AsynchronousDeliveryStrategy" />
      
      
      
      <producerConfig>bootstrap.servers=localhost:30400,localhost:30401</producerConfig>
      
      <producerConfig>acks=0</producerConfig>
      
      <producerConfig>linger.ms=1000</producerConfig>
      
      <producerConfig>max.block.ms=0</producerConfig>
      
      
      
      <producerConfig>security.protocol=SASL_SSL</producerConfig>
      <producerConfig>sasl.mechanism=PLAIN</producerConfig>
      <producerConfig>ssl.endpoint.identification.algorithm=</producerConfig>
      <producerConfig>ssl.truststore.location=/certs/kafka.client.truststore.jks</producerConfig>
      <producerConfig>ssl.truststore.password=mypwd</producerConfig>
      <producerConfig>sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="";</producerConfig>
      
      
  </appender>
<logger name="custom.logger" additivity="false">
    <level value="INFO"/>
    <appender-ref ref="KAFKA" />
  </logger>
<root level="ERROR">
     <appender-ref ref="STDOUT" />
</root>

**Comment by danielwegener** [comment]
I think this question can be answered best by the logback documentation. This project here is a plain logback appender. Configuring log loggers is out of scope.
