### ISSUE TITLE
Support for Kafka 0.8.2.1

### ISSUE THREAD

**Issue by fabiodellanna** [danielwegener/logback-kafka-appender#12]
Hi, 
I was wondering when version 0.0.3 will be released. 

I'm using logback-kafka-appender to send messages to Kafka 0.8.2.1 and I see that version 0.0.2 uses Kafka 0.8.2.0 in pom.xml.

Thanks.

**Comment by danielwegener** [comment]
Good point, totally forgot about that one :)

https://github.com/danielwegener/logback-kafka-appender/releases/tag/logback-kafka-appender-0.0.3

**Comment by fabiodellanna** [comment]
Great job!
