### ISSUE TITLE
Would benefit from being able to use the generic Logstash encoder

### ISSUE THREAD

**Issue by LouPaloma** [danielwegener/logback-kafka-appender#13]
Interested in a class that implements as: 

public class KafkaJSONMessageEncoder<E> extends LoggingEventCompositeJsonEncoder implements KafkaMessageEncoder<E>, LifeCycle {}

???
This would allow an encoder to be configured that can handle Logstash timezone adjustments AND custom pattern layouts (instead of all the canned Logstash overhead) looks like this:

		-->
		<encoder class="com.github.danielwegener.logback.kafka.encoding.KafkaJSONMessageEncoder">
			<timeZone>UTC</timeZone>

			<providers>
				<timestamp/>

				<pattern>
					<pattern>
						{"message": "%replace(%msg){'blahblah: ', ''}" }
					</pattern>
    			</pattern>
  			</providers>
		</encoder>

I have a sample source if your interested.

**Comment by danielwegener** [comment]
Hi @LouPaloma 

Thank you for your suggestion! Yet, I see this module rather as plain "can push bytes to kafka". Your LoggingEventCompositJsonEncoder is already specific to JSON/Logstash. I agree that using json/logstash together with the logback-kafka-appender is a common use case, but I'd like to keep this module unopinionated towards that (for now) - to keep it as simple and maintainable as possible.
But I'd really welcome it if you would publish your implementation as Gist, Blog post or even its own maven module and I will be happy to reference to it from the readme.

Would that be okay for you?

Kind regards

**Comment by danielwegener** [comment]
@LouPaloma I will close this issue for now. Feel free to reopen it if you feel the need.
