### ISSUE TITLE
Springboot 1.3.0: LogbackLoggingSystem failed while loading KafkaAppenderConfig if no keyingStrategy is configured

### ISSUE THREAD

**Issue by soniro** [danielwegener/logback-kafka-appender#17]
When using `logback-kafka-appender` with `spring-boot 1.3.0.RELEASE` the `LogbackLoggingSystem` fails while loading the `KafkaAppenderConfig` when no `keyingStrategy` is defined in the `logback-kafka.xml`.

This is because of an implementation change in Springboots's `LogbackLoggingSystem`, scanning the logger context status manager for errors and throwing an exception if at least one error was detected (in the former version, it always throws an exception if it catches an exception before).

There is a default keying strategy defined so it is not necessary to log it as an error. An info (like it's used for the `deliveryStrategy`) should be fine.

**Workaround:** Just define the default `keyingStrategy` explicitly in your `logback-kafka.xml`:
    <keyingStrategy class="com.github.danielwegener.logback.kafka.keying.RoundRobinKeyingStrategy" />

**Comment by danielwegener** [comment]
Thanks for the report. Your PR is flawless. Do you need a release soon or can we bundle up the next release with #11 ?

**Comment by soniro** [comment]
As we have a workaround the release is not that urgent. If #11 won't take that long to fix we can wait. But it would be super awesome if we could get a release in the next two weeks so we can close this topic.
