### ISSUE TITLE
Need for a Json Message Encoder

### ISSUE THREAD

**Issue by rubesMN** [danielwegener/logback-kafka-appender#21]
My IT group who maintains Logstash/ElasticSearch/Kibana tells me I have to put JSON formatted messages on my Kafka Queue for logstash to pull out.   I see you do not provide an encoder which supports writing to JSON or to the format expected by Logstash.   I tried using [logstash-logback-encoder]  (https://github.com/logstash/logstash-logback-encoder), but it looks like they are incompatible:

> ERROR in ch.qos.logback.core.joran.util.PropertySetter@7d1b7c86 - A "net.logstash.logback.encoder.LogstashEncoder" object is not assignable to a "com.github.danielwegener.logback.kafka.encoding.KafkaMessageEncoder" variable.
> ERROR in com.github.danielwegener.logback.kafka.KafkaAppender[kafkaAppender] - No encoder set for the appender named ["kafkaAppender"].

Is there any hope for writing to a JSON formatted string?

**Comment by danielwegener** [comment]
Hi @rubesMN !
You are right, logback-kafka-appender does not support common logback encoders (please read https://github.com/danielwegener/logback-kafka-appender#serialization). The point is, that logback encoders use java OutputStreams (see http://logback.qos.ch/apidocs/ch/qos/logback/core/encoder/Encoder.html) which do not particularly are a very good fit for the kafka producer api. So either you roll your own serializer by wrapping a [LogstashEncoder](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/encoder/LogstashEncoder.java) or we find a more general mechanism to wrap a LogstashEncoder into a KafkaAppender.

**Comment by tendant** [comment]
I am using LogstashEncoder with logback-kafka-appender directly. It works fine in my case.

Here is the encoder configuration:

```
    <encoder class="com.github.danielwegener.logback.kafka.encoding.PatternLayoutKafkaMessageEncoder">
      <layout class="net.logstash.logback.layout.LogstashLayout" />
    </encoder>
```

You might need to add logstash-logback-encoder to your dependency. Here is what I am using:

 [net.logstash.logback/logstash-logback-encoder "3.4"]

Hope this helps.

**Comment by danielwegener** [comment]
Yeah thats how it is supposed to be used :)

**Comment by danielwegener** [comment]
@rubesMN I think that most string based protocols could ship a `Layout` that can be used by logback-kafka-appender directly (as mentioned by @tendant for logstash, I see this as the main use-case too). Protocols that require an encoder (maybe because they are binary) will indeed need a custom wrapper but I do not yet see them as part of this module. Feel free to reopen this issue if you have the need.

I'll add a FAQ entry to the README for the logback use case.

**Comment by PankajRoy1983** [comment]
HI, I am trying to use 
<appender name="KAFKA" class="com.github.danielwegener.logback.kafka.KafkaAppender">
       <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
			<level>INFO</level>
		</filter>

		<encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
ERROR 👍 
20:39:54,018 |-ERROR in ch.qos.logback.core.joran.util.PropertySetter@71dac704 - A "ch.qos.logback.classic.encoder.PatternLayoutEncoder" object is not assignable to a "com.github.danielwegener.logback.kafka.encoding.KafkaMessageEncoder" variable.
20:39:54,018 |-ERROR in ch.qos.logback.core.joran.util.PropertySetter@71dac704 - The class "com.github.danielwegener.logback.kafka.encoding.KafkaMessageEncoder" was loaded by 
20:39:54,018 |-ERROR in ch.qos.logback.core.joran.util.PropertySetter@71dac704 - [org.springframework.boot.loader.LaunchedURLClassLoader@5d099f62] whereas object of type 
20:39:54,018 |-ERROR in ch.qos.logback.core.joran.util.PropertySetter@71dac704 - "ch.qos.logback.classic.encoder.PatternLayoutEncoder" was loaded by [org.springframework.boot.loader.LaunchedURLClassLoader@5d099f62].

Can you please assist

**Comment by danielwegener** [comment]
What version the `logback-kafka-encoder` are you using?
