### ISSUE TITLE
Extra line \n in the logback-kafka-appender output

### ISSUE THREAD

**Issue by dianedownie** [danielwegener/logback-kafka-appender#27]
While attempting to consume my logback-access configuration, I noticed I'm getting an extra \n in the data stream.  This is causing my consumer to see an empty row.  For example,
```
{"message":"POST /kbmatch/api/v1/matches/simple HTTP/1.1","host":"bds00931","client":"127.0.0.1","date":"2016-02-11 16:54:10","verb":"POST","request":"/kbmatch/api/v1/matches/simple","httpversion":"HTTP/1.1","response":"200","bytes":"-","requestTime":"20","AuthToken":"xxx","CorrelationID":"MatchTest.jmx|Signatures-3-10-58.log","User-Agent":"Test/2.4.0-SNAPSHOT (Macintosh; Intel Mac OS X 10_10_5)"}

{"message":"POST /kbmatch/api/v1/matches/simple HTTP/1.1","host":"bds00931","client":"127.0.0.1","date":"2016-02-11 16:54:10","verb":"POST","request":"/kbmatch/api/v1/matches/simple","httpversion":"HTTP/1.1","response":"200","bytes":"-","requestTime":"19","AuthToken":"xxx","CorrelationID":"MatchTest.jmx|Signatures-3-10-59.log","User-Agent":"Test/2.4.0-SNAPSHOT (Macintosh; Intel Mac OS X 10_10_5)"}

{"message":"POST /kbmatch/api/v1/matches/simple HTTP/1.1","host":"bds00931","client":"127.0.0.1","date":"2016-02-11 16:54:10","verb":"POST","request":"/kbmatch/api/v1/matches/simple","httpversion":"HTTP/1.1","response":"200","bytes":"-","requestTime":"25","AuthToken":"xxx","CorrelationID":"MatchTest.jmx|Signatures-3-10-6.log","User-Agent":"Test/2.4.0-SNAPSHOT (Macintosh; Intel Mac OS X 10_10_5)"}
```
I don't believe this is a logback-access behavior, as I don't see this with the same data pattern in the logback.core.rolling.RollingFileAppender.  

Any idea what might be causing this or how I can avoid it?

Perhaps both Kafka and logback-access are each adding an \n?
Here's my pattern
```
            <encoder class="com.github.danielwegener.logback.kafka.encoding.LayoutKafkaMessageEncoder">
                <charset>UTF-8</charset>                
                <layout class="ch.qos.logback.access.PatternLayout">
                    <pattern>%h %l %u %t{yyyy-MM-dd HH:mm:ss} "%r" %s %b %D :%i{X-BDS-AuthToken}:%i{X-BDS-CorrelationID} :%i{User-Agent}</pattern>
<!--
                    <pattern>{"message":"%r","host":"${HOSTNAME}","client":"%h","date":"%t{yyyy-MM-dd HH:mm:ss}","verb":"%m","request":"%U","httpversion":"%H","response":"%s","bytes":"%bytesSent","requestTime":"%D","AuthToken":"%i{X-BDS-AuthToken}","CorrelationID":"%i{X-BDS-CorrelationID}","User-Agent":"%i{User-Agent}"}</pattern>
-->
                </layout>
            </encoder>
```

**Comment by dianedownie** [comment]
I see that some of this is in logback-access itself.  Possibly Kafka is doing it as well thus the double line separation.
[http://logback.qos.ch/xref/ch/qos/logback/access/pattern/EnsureLineSeparation.html](EnsureLineSeparation)

**Comment by danielwegener** [comment]
May I ask what kind of consumer you use? I'd say that kafka messages themself do normally not need a line separator, they are separated by "message-borders". For a consumer that prints to stdout or something it naturally makes sense to print newlines between messages (the simple consumer from the kafka examples does).
I wonder if one could turn off the `EnsureLineSeparation` by configuring an empty `postCompileProcessor` as in http://logback.qos.ch/xref/ch/qos/logback/access/PatternLayout.html#L178. 

You could try something like this:
```xml
<layout class="ch.qos.logback.access.PatternLayout">
    <pattern>...</pattern>
   <postCompileProcessor></postCompileProcessor>
</layout>
``` 
(not too sure if joran likes nulls though)

**Comment by dianedownie** [comment]
Thanks for your quick response.  I see this behavior in both consumers I'm working with: the console consumer and Flume.  In looking at http://www.javased.com/?source_dir=logback/logback-access/src/main/java/ch/qos/logback/access/pattern/EnsureLineSeparation.java it appears to only add a newline character if it doesn't already find one.  My guess would be that something else is also inserting a newline and that the logback-access processor is first on the list.  I will try your suggestion when I get the chance, but still looking for another newline.

**Comment by danielwegener** [comment]
My understanding:
- The container logs: `foo` 
- `EnsureLineSeparation` adds a newline (because - well - just because): `foo\n`
- logback-kafka-appender writes exactly this to kafka
- kafka console consumer [adds a newline](https://github.com/apache/kafka/blob/9220df9f8b58870a2282d3e4ceb2e003667d854b/core/src/main/scala/kafka/tools/ConsoleConsumer.scala#L365) (`foo\n\n`) and prints it to stdout 
```
foo

```

So there is exactly one newline too much and that comes from `EnsureLineSeparation`

**Comment by dianedownie** [comment]
Ah.  My flume HDFS sink config is doing that as well.  (doh)
```
kbactivity1.sinks.kb_service_activity_hdfs.hdfs.serializer.appendNewLine=true
```

**Comment by danielwegener** [comment]
Have you tried the empty `<postCompileProcessor></postCompileProcessor>`-setting? It may be worth to mention in the FAQ.

**Comment by danielwegener** [comment]
@dianedownie Ah, and feel free to close the issue :)

**Comment by dianedownie** [comment]
The empty <postCompileProcessor></postCompileProcessor> had no effect, so presumably the default EnsureLineSeparation post process is still in effect.
Haven't been able to test my flume HDFS sink config as cluster was down, but I have confidence that will work.
But yes, sorry for being remiss in not closing this issue sooner.
Thanks again, @danielwegener .

**Comment by dianedownie** [comment]
@danielwegener as I follow-up I found that flume HDFS sink as well other flume sinks supports [an event serializer](https://flume.apache.org/FlumeUserGuide.html#event-serializers)  which can be configured.  By default it will serialize text and default to adding a \n to each event.  This can be configured within the sink configuration:
```
agent-name.sinks.hdfs-sink-name.serializer = text
agent-name.sinks.hdfs-sink-name.serializer.appendNewline = false
```

**Comment by danielwegener** [comment]
Hi @dianedownie - cheers for giving an update on this. I still think we should find a solution so the `\n` does not end up in the kafka message in the first place.

**Comment by dianedownie** [comment]
It seems like that should be possible with logback give the designation of "default" post process.  I was unable to discover a way to disable that behavior.
