### ISSUE TITLE
Logback AsyncAppender

### ISSUE THREAD

**Issue by marmanan** [danielwegener/logback-kafka-appender#34]
It´s still recommended to wrap KafkaAppender into a Logback AsyncAppender when using kafka client 0.9 or above to prevent blocking? 

Thanks

**Comment by danielwegener** [comment]
@marmanan  Unfortunately kafka 0.9 still behaves blocking until the initial connection to the cluster is made or if the connection to the cluster is lost for a longer period of time (and the meta-data knowledge about the cluster becomes invalid). So if you want to keep your application responsive at the cost of loosing some log messages while kafka is not reachable, I'd still recommend to use the AsyncAppender
