### ISSUE TITLE
Cannot connect to Kafka > 0.9

### ISSUE THREAD

**Issue by lostiniceland** [danielwegener/logback-kafka-appender#41]
The current version uses kafka-client 0.9.0 which is not working with newer releases of Kafka (as of today 0.10.1.1).

With Kafka 0.10 Java 8 is necessary even when still using the Scala 2.11 build, so changing the version will be a breaking change

**Comment by lostiniceland** [comment]
After creating a snapshot version with the forementioned changes it seems my problem is not related to the used kafka-client.

I am trying to get the Appender running in a Akka environment with Scala 2.12
https://github.com/lostiniceland/playground/tree/log-kafka-appender/akka-demo/akka-kafka/src/main

I am able to connect to kafka just fine using the Producer in the master-branch, but somehow the logback-appender cannot because of a timeout during metadata-update

`23:29:56.130 [KafkaSystem-akka.actor.default-dispatcher-2] DEBUG o.a.k.clients.producer.KafkaProducer - Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 1000 ms.`

**Comment by lostiniceland** [comment]
After further debugging it turns out that in my environment the partitionsCount cannot be read

**Comment by danielwegener** [comment]
Thanks for the elaborated report anyway :) And sorry for my miserable response time.
