### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by IngvarJackal** [danielwegener/logback-kafka-appender#43]
Hello, there's a NullPointerException in [AsynchronousDeliveryStrategy](https://github.com/danielwegener/logback-kafka-appender/blob/master/src/main/java/com/github/danielwegener/logback/kafka/delivery/AsynchronousDeliveryStrategy.java#L18) (producer is null) with following config:
```xml
<appender name="KAFKA" class="com.github.danielwegener.logback.kafka.KafkaAppender">
    <encoder class="com.github.danielwegener.logback.kafka.encoding.LayoutKafkaMessageEncoder">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%d{"yyyy-MM-dd HH:mm:ss,SSS"} %level [%X{project}] [%X{parentid}] \(%thread\) %logger{15}: %m
                -------------------------------------------------------------------------------%n
            </pattern>
        </layout>
    </encoder>
    <topic>ihorlogs</topic>
    <keyingStrategy class="com.github.danielwegener.logback.kafka.keying.HostNameKeyingStrategy" />
    <deliveryStrategy class="com.github.danielwegener.logback.kafka.delivery.AsynchronousDeliveryStrategy" />
    <producerConfig>bootstrap.servers=localhost:9992</producerConfig>
    <producerConfig>acks=0</producerConfig>
    <producerConfig>linger.ms=100</producerConfig>
    <producerConfig>block.on.buffer.full=false</producerConfig>
    <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
        <evaluator class="ch.qos.logback.classic.boolex.GEventEvaluator">
            <expression>
                e.mdc?.get("project").contains("ururu.projects")
            </expression>
        </evaluator>
        <OnMismatch>DENY</OnMismatch>
        <OnMatch>NEUTRAL</OnMatch>
    </filter>
</appender>
```
Any idea why?

**Comment by IngvarJackal** [comment]
P.S. I'm running [that](https://mvnrepository.com/artifact/com.github.danielwegener/logback-kafka-appender/0.1.0) jar on wildfly.

**Comment by danielwegener** [comment]
Hi @IngvarJackal and thanks for your report. Sorry for the delayed response. Could you check if the NPE still happens when you remove the `<filter>? To be honest, I have not yet looked into the whole filter mechanic. Nevertheless, a stack trace would be very very helpful!

**Comment by IngvarJackal** [comment]
@danielwegener I found the root cause: https://issues.apache.org/jira/browse/KAFKA-3218
The producer failed to instantiate in my case because of mentioned kafka issue, but **without any messages in stdout or stacktraces** at our servers. So I implemented own much simpler appender.
