### ISSUE TITLE
How to exclude messages

### ISSUE THREAD

**Issue by pradeepkusingh** [danielwegener/logback-kafka-appender#48]
I have mixed bags of Json and string messages and would like to avoid sending simple string messages. How can I do that ?

**Comment by danielwegener** [comment]
just a thought :)
- json-objects are strings and therefore hard/expensive to distinguish from "messages": (is "{}" a json string or maybe just a a crude log message? should id be filtered?)
- logback is a logging framework (primarily) working with strings
=> use something different to write json objects to a kafka topic (e.g. a kafka client) and to not sneak them through a logging framework.

Of course you could also use a dedicated logger that is tied to an kafka-appender for your json objects. But well. It's not really meant to be used like that :)
