### ISSUE TITLE
build not success

### ISSUE THREAD

**Issue by TonnyCheng** [danielwegener/logback-kafka-appender#57]
Hi, bro
i want try to build source from your repository, But a error happened in this class of KafkaAppender,
At line 118,  Are you sure have this method of 'encode'?

**Comment by danielwegener** [comment]
Which branch (or commit) do you try to build? I am pretty sure that the master builds works  :) (see https://travis-ci.org/danielwegener/logback-kafka-appender/builds/325208410)
