### ISSUE TITLE
Using custom KeyStore tool for Kafka ProducerConfigs

### ISSUE THREAD

**Issue by AshishHNP** [danielwegener/logback-kafka-appender#63]
Hello, I was looking to use this logback-kafka-appender in Heroku. The Kafka I am interacting with will be set up with ssl. I want to try to use: https://github.com/heroku/env-keystore . I will have certs and keys as environment variables. I was thinking of modifying producer configs for this reason and use it to set up the KeyStore dynamically.
This isn't really an issue but wanted to know if anyone has done anything like this?

**Comment by danielwegener** [comment]
To be discussed in #64

**Comment by danielwegener** [comment]
out of scope, see discussion in #64
