### ISSUE TITLE
about 0.1.0 update 0.2.0

### ISSUE THREAD

**Issue by qq12157138** [danielwegener/logback-kafka-appender#68]
0.1.0 have LayoutKafkaMessageEncoder.class
0.2.0 not fount

why???

**Comment by danielwegener** [comment]
see https://github.com/danielwegener/logback-kafka-appender/releases/tag/untagged-148a18198f0c5ccc0401 (no. 2)
https://github.com/danielwegener/logback-kafka-appender/issues/51
