### ISSUE TITLE
Its not working with String serializer/ deserializer

### ISSUE THREAD

**Issue by anhtv08** [danielwegener/logback-kafka-appender#69]
Hi,
I tried to configure the different value Serializer for producer but it is not working.

My configuration as below

```   <producerConfig>value.serializer=org.apache.kafka.common.serialization.StringSerializer</producerConfig>
        <producerConfig>key.serializer=org.apache.kafka.common.serialization.StringSerializer</producerConfig>
```
When I remove this change and use `ByteArraySerializer` it is working as normal.

@danielwegener  Can you please explain?

**Comment by danielwegener** [comment]
No problem :) With this appender you want to transform an `ILoggingEvent` to a byte array that can be written (and compressed) to a kafka topic. As described in https://github.com/danielwegener/logback-kafka-appender#custom-serialization you can plug in any another logback `Encoder` mechanism that encodes an `ILoggingEvent` to a byte array.

So works like this: `Encoder(ILoggingEvent) -> byte[]` and then `ByteArraySerializer(byte[]) -> byte[]`. Any other `KafkaSerializer` like the mentioned `StringSerializer` or even the `KafkaAvroSerializer ` can not work with `byte[]`, they expect a string or an object with a well known Avro scheme respectively.

So what you are looking for is either a logback `Encoder` for avro OR a generic Encoder/Serializer mechanism that would allow arbitrary interim formats and not only `byte[]`.
The former I am not aware if they exist, the latter would be a new feature request for this appender.

**Comment by danielwegener** [comment]
But my first question should have been: What are you trying to achieve? :)

**Comment by danielwegener** [comment]
Closed due to inactivity
