### ISSUE TITLE
Support for Zookeeper of Kafka

### ISSUE THREAD

**Issue by huanying1988** [danielwegener/logback-kafka-appender#71]
I tried to send topic message using zookeeper address of Kafka cluster, but failed. Does logback-kafka-appender support to send kafka message using zookeepers?

**Comment by danielwegener** [comment]
As far as I know (knowledge from kafka 0,8), kafka clients are not supposed to directly communicate with a zookeeper. The ZK is only the consensus backend for the broker pool. A client (producer or all "new" consumers) must always know a subset of all brokers to connect to (they'll learn of other brokers in the pool automatically).
