### ISSUE TITLE
How to customize the message format

### ISSUE THREAD

**Issue by BraveWay** [danielwegener/logback-kafka-appender#72]
How to customize the message format. Like this.
<encoder charset="UTF-8">
            <pattern>{"appname":"${appName}","ip":"%ip","time": "%date{yyyy-MM-dd HH:mm:ss.SSS}","thread": "%thread","level": "%level","class": "%logger{36}","message": "%message"}</pattern>      
          </encoder>

I want to get the correct JSON format
thank you

**Comment by danielwegener** [comment]
What encoder are you using? Please refer to the documentation of your logback encoder.

**Comment by danielwegener** [comment]
Close due to inactivity
