### ISSUE TITLE
Does this appender is supported to connect to kafka-cluster?

### ISSUE THREAD

**Issue by HellxZ** [danielwegener/logback-kafka-appender#85]
Does this appender is supported to connect to kafka-cluster?
I have launch a single kafka, it works.
but , i use "bootstrap-server"to set “kafka1:9092,kafka2:9092,kafka3:9092”,
the appender warnning my cluster id and the project can't bootstrap complete.

**Comment by danielwegener** [comment]
Yes this appender is supposed to work with multiple brokers. Setting multiple bootstrap servers according to the kafka producer documentation should be possible. Please provide your full appender configuration and the error messages shown.

Also note that, even if your appender only knows one bootstrap server, it will learn of other brokers by the topic meta data exchange with your single bootstrap server.

**Comment by HellxZ** [comment]
Okay, i will speak shortly.
I have use docker image `wurstmeister/kafka` to start a kafka cluster, and set the KEYs kafka1/kafka2/kafka3 to `/etc/hosts`，the VAL are vm's IP.
My configuration is:
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>%d{HH:mm:ss.SSS} [%thread] %-5level logger_name:%logger{36} - message:%msg%n</Pattern>
        </layout>
    </appender>

    <logger name="com.example.demo" level="INFO"/>

    <appender name="diy-kafka-appender" class="com.github.danielwegener.logback.kafka.KafkaAppender">
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level logger_name:%logger{36} - message:%msg%n</pattern>
        </encoder>
        <topic>all_logs</topic>
        
        <keyingStrategy class="com.github.danielwegener.logback.kafka.keying.HostNameKeyingStrategy" />
        
        <deliveryStrategy class="com.github.danielwegener.logback.kafka.delivery.BlockingDeliveryStrategy">
            <timeout>0</timeout>
        </deliveryStrategy>
        <producerConfig>bootstrap.servers=kafka1:9091,kafka2:9092,kafka3:9093</producerConfig>
        <producerConfig>buffer.memory=8388608</producerConfig>
        <producerConfig>metadata.fetch.timeout.ms=99999999999</producerConfig>
        <producerConfig>client.id=${HOSTNAME}-${CONTEXT_NAME}-logback-restrictive</producerConfig>
        <producerConfig>compression.type=gzip</producerConfig>
    </appender>
    <root level="INFO">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="diy-kafka-appender" />
    </root>
</configuration>`

I also set the hosts about kafka1/kafka2/kafka3 to my vm'IP,

ahh....when i try to reproduce the bug，but it works now.....

**Comment by danielwegener** [comment]
Glad I could help 😊
