### ISSUE TITLE
How to customize the kafka key

### ISSUE THREAD

**Issue by Jaywoods2** [danielwegener/logback-kafka-appender#88]
Due to the limited number of our kafka topic, I want to have multiple applications share a topic, then logstash reads the kafka key as an elastic index,how can I customize the keys?

**Comment by danielwegener** [comment]
I can warmly recommemd the readme section on keying Strategies: https://github.com/danielwegener/logback-kafka-appender/blob/master/README.md#keying-strategies--partitioning

**Comment by Jaywoods2** [comment]
thank you very much for your support /:rose
